### ISSUE TITLE
Can't make it work on firefox

### ISSUE THREAD

**Issue by PeadarO** [svarunan/serverless-webrtc#6]
Hello Svarunan, I have installed the software on two machines that are behind the same router. They are running Windows 10 and the latest version of Microsoft Edge. I followed the instructions and no connection was made. Nothing happened. I then ran it on the same two machines using Mozilla Firefox. Clicking the "CreateOffer" button had no effect. It might be a problem with the latest version of Firefox. It is ignoring the CreateOffer and Answer buttons completely but it seems to try to obey the Send and Browse buttons. 
This looks like a very useful piece of work but so far I have not made it do anything on Firefox
.  Peadar.

**Comment by PeadarO** [comment]
I have read the previous tip from another user so I amended the code slightly.

//	local.src = URL.createObjectURL(stream);

    local.srcObject=stream;
    local.play();

I did this with the local and remote streams. It fixed the issue for Microsoft Edge but not Firefox.  Peadar

**Comment by PeadarO** [comment]
Hi again Svarunan, I have tried again running with Edge and I can see that the line that is not performing is 
<form action="" onsubmit="event.preventDefault(); return sendMsg();">     
The sendMsg() is not being called. I'll try again with Firefox tomorrow.
Peadar

**Comment by PeadarO** [comment]
Hi Svarunan, The program cannot be run with Firefox at all because the "CreateOffer" button is dead but it works with the latest version of Microsoft Edge.    Peadar

**Comment by PeadarO** [comment]
I have been exploring the code of this program and it has been very worthwhile. I would like to ask this question of Svarunan or anyone else (If it is a fair question). I am trying to change the code so that I can hard code the IPAddress and port number into both clients, and thus get rid of the hash altogether. I hoped I would find the IPaddress and portnumber in the _remoteOffer.sdp variable but I have not. Can anyone tell me where the IPAdress is? When I put the hash from machine one to machine two to make the offer. Then put the hash from machine two to machine one to give the acceptance then machine one is ready to make contact and it must then have the IPAddress and port number for machine two but I cannot find it in the code. Any ideas anyone?

**Comment by svarunan** [comment]
All firefox related issues are fixed.
