### ISSUE TITLE
"Serverless"?

### ISSUE THREAD

**Issue by Quotatron3000** [svarunan/serverless-webrtc#9]
In your code: var conf = { iceServers: [{"urls":"stun:stun.l.google.com:19302"}] };

If it is serverless, why do you require the Google STUN server in your code?

**Comment by svarunan** [comment]
Server-less meaning, You don't need Signalling server for initial handshake to connect/transfer the SDP from peer A and peer B. This repo is mainly for people who need to understand the webrtc with minimal setup. 
If you're trying this on same browser or on two diff laptops with same n/w try setting `{ iceServers: [] };` and it will still work.
use of `ice` and `turn` is when you're on two diff public network and behind double nat. hope this helps.
